- hosts: "{{apb_host}}"
  gather_facts: no
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    proxy_env:
      http_proxy: "{{apb_http_proxy}}"
      https_proxy: "{{apb_http_proxy}}"
      HTTP_PROXY: "{{apb_http_proxy}}"
      HTTPS_PROXY: "{{apb_http_proxy}}"
      NO_PROXY: "localhost,127.0.0.1"
      no_proxy: "localhost,127.0.0.1"

  tasks:
    - name: running shell
      shell:
        cmd: "{{apb_shell | expanduser}}"
      environment: "{{proxy_env}}"
      register: apb_shell_output
      retries: 5
      until: apb_shell_output.rc == 0 and apb_shell_output.stderr.find("error") == -1 and apb_shell_output.stderr.find("fatal") == -1
      delay: 1
      when: apb_runtype == "shell"

    - debug:
        msg:
          - name:{{u_name | default("")}}
          - describe:{{u_describe | default("")}}
          - "stdout:"
          - "{{ apb_shell_output.stdout_lines }}"
          - "stderr:"
          - "{{ apb_shell_output.stderr_lines }}"
      when: apb_runtype == "shell"

    - name: running script
      ansible.builtin.script: "{{apb_script | expanduser}}"
      environment: "{{proxy_env}}"
      register: apb_script_output
      retries: 5
      until: apb_script_output.rc == 0 and apb_script_output.stderr.find("error") == -1 and apb_script_output.stderr.find("fatal") == -1
      delay: 1
      when: apb_runtype == "script"

    - debug:
        msg:
          - name:{{u_name | default("")}}
          - describe:{{u_describe | default("")}}
          - "stdout:"
          - "{{ apb_script_output.stdout }}"
          - "stderr:"
          - "{{ apb_script_output.stderr }}"
      when: apb_runtype == "script"
